version: '3'
services:
 db:
   image: mysql:8.0.39
   container_name: pinkFlamingosContainer
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=asd3129760162
     - MYSQL_DATABASE=bookme
   volumes:
     - ./db:/var/lib/mysql